on:
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        env: 
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get -y update
          sudo apt-get install -y --no-install-recommends curl gnupg software-properties-common
          curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-add-repository "deb http://apt.llvm.org/`lsb_release -c | cut -f2`/ llvm-toolchain-`lsb_release -c | cut -f2`-19 main"
          sudo apt-get install -y --no-install-recommends autoconf cmake ninja-build gcc g++ linux-tools-common linux-tools-generic libtool llvm-19-dev lld-19 clang-19 libomp-19-dev libopenmpi-dev openmpi-bin git make imagemagick ffmpeg
          sudo apt-get autoremove -y --purge
          sudo apt-get clean -y
          sudo rm -rf /var/lib/apt/lists/*

          # sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-19 10 --slave /usr/bin/clang++ clang++ /usr/bin/clang++-19
          sudo update-alternatives --install /usr/bin/opt opt /usr/bin/opt-19 10
          sudo update-alternatives --install /usr/bin/lld lld /usr/bin/lld-19 10
          sudo update-alternatives --install /usr/bin/llvm-symbolizer llvm-symbolizer /usr/bin/llvm-symbolizer-19 10

          sudo ln -s /usr/bin/convert /usr/bin/magick

          sudo apt-get -y update
          sudo apt-get -y install golang-go graphviz libgoogle-perftools-dev
          go install github.com/google/pprof@latest
      - name: Run tests
        id: run_tests
        run: |
          make -j
          OUTPUT=$(./run_tests.sh)
          OUTPUT_STATUS=$?
          echo "PAYLOAD<<EOF"$'\n'"$OUTPUT"$'\n'EOF >> "$GITHUB_OUTPUT"
          echo "$OUTPUT"
          exit $OUTPUT_STATUS
      - uses: actions/github-script@v7
        env:
          body: ${{ steps.run_tests.outputs.PAYLOAD }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.body
            })
